### PR TITLE
Add support for http proxy

### PR DESCRIPTION
**Pull request by corecanarias**
proxy_from_url() function will return an implementation of
PoolManager with support to send requests through a proxy

### CODE REVIEW

**Comment by wavefront-mike** [comment]
@conorbev: My update and recent merge caused this conflict.  Add`'timeout': urllib3.Timeout(connect=10.0, read=5.0)` to `pool_manager_options` and that will fix this conflict.  The final lines should look like this:

```
...
        # https pool manager
        pool_manager_options = {
            'num_pools': pools_size,
            'cert_reqs': cert_reqs,
            'ca_certs': ca_certs,
            'cert_file': cert_file,
            'key_file': key_file,
            'timeout': urllib3.Timeout(connect=10.0, read=5.0)
        }
        # https pool manager
        if 'https_proxy' in os.environ:
            self.pool_manager = urllib3.proxy_from_url(
                os.environ['https_proxy'],
                **pool_manager_options
            )
        else:
            self.pool_manager = urllib3.PoolManager(**pool_manager_options)

    def request(self, method, url, query_params=None, headers=None,
...
```

**Comment by corecanarias** [comment]
I've added the change. But I guess having a way to change that values would be good.

**Comment by wavefront-mike** [comment]
Thanks @corecanarias!   This code is actually generated from [swagger-codegen](https://github.com/swagger-api/swagger-codegen).  We should probably push most of these changes up to them (with a way to configure each of these settings).  For now, we're just maintaining it on our own to check the reliability of this code generator.

**Comment by corecanarias** [comment]
Fixed the conflict. 

I didn't see the comment about swagger-codegen. Never used that, really. But definitely should have something to support proxy...

**Pull request merged**
